version: '2.15.1'
services:
  item-app:
    image: franda/item-app
    ports:
      - "8080:80"
    depends_on:
      - item-db

  item-db: 
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: